### ISSUE TITLE
如何生成DTW matrix、traffic pattern set呢？

### ISSUE THREAD

**Issue by ZPFPHD** [BUAABIGSCity/PDFormer#12]
作者您好，如何生成DTW matrix、traffic pattern set呢？

**Comment by NickHan-cs** [comment]
您好，感谢您的提问！我们的代码已经实现了这两个功能，具体可参考 https://github.com/BUAABIGSCity/PDFormer/blob/master/libcity/data/dataset/pdformer_dataset.py#L33 和 https://github.com/BUAABIGSCity/PDFormer/blob/master/libcity/data/dataset/pdformer_dataset.py#L117 ，运行代码时会自动生成DTW matrix和traffic pattern set。
