### ISSUE TITLE
关于single和average的评估模式。

### ISSUE THREAD

**Issue by zhz-bit** [BUAABIGSCity/PDFormer#13]
看到你们的源码中选择使用的是使用的average的评估方式，请问你们对比的所有模型的测试指标也是基于average的评估方式吗？

**Comment by aptx1231** [comment]
对



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhz ***@***.***&gt;
发送时间: 2023年8月26日 10:49
收件人: BUAABIGSCity/PDFormer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [BUAABIGSCity/PDFormer] 关于single和average的评估模式。 (Issue #13)





 
看到你们的源码中选择使用的是使用的average的评估方式，请问你们对比的所有模型的测试指标也是基于average的评估方式吗？

**Comment by zhz-bit** [comment]
![image](https://github.com/BUAABIGSCity/PDFormer/assets/50071503/3224196e-84dc-4f4d-966a-a5c7e10ed189)
看到你们在"Towards Efficient and Comprehensive Urban Spatial-Temporal Prediction: A Unified Library and Performance Benchmark"这篇文章中DCRNN复现结果和pdformer中DCRNN的评估方式有什么区别吗？
![image](https://github.com/BUAABIGSCity/PDFormer/assets/50071503/71bf5e2c-5839-4796-af1b-65a7a59e51eb)

**Comment by aptx1231** [comment]
那个是single，另外数据切分比例是712，这个是622



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhz ***@***.***&gt;
发送时间: 2023年8月26日 11:04
收件人: BUAABIGSCity/PDFormer ***@***.***&gt;
抄送: Jiawei Jiang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [BUAABIGSCity/PDFormer] 关于single和average的评估模式。 (Issue #13)





 

 看到你们在"Towards Efficient and Comprehensive Urban Spatial-Temporal Prediction: A Unified Library and Performance Benchmark"这篇文章中DCRNN复现结果和pdformer中DCRNN的评估方式有什么区别吗？
