### ISSUE TITLE
关于用于traffic speed的预测

### ISSUE THREAD

**Issue by suzy0223** [BUAABIGSCity/PDFormer#14]
您好 PEMS07的add_time_in_day和和add_day_in_week 为true时模型运行存在问题，没有执行添加对应的day和time维度，相同的设置在PEMS08数据集上就可以运行。

**Comment by aptx1231** [comment]
不好意思，错过了这个邮件，回复的比较晚。

可以检查一下log文件中load_external参数是否是True，这俩代码是一样的，正常不会因为数据而有区别。
