### ISSUE TITLE
关于数据集划分的测试集test和最终输出的预测npz文件中数量不一致的问题

### ISSUE THREAD

**Issue by siyuan1127** [BUAABIGSCity/PDFormer#15]
![36H2WC@WSPKKRANV~{J1ONI](https://github.com/BUAABIGSCity/PDFormer/assets/130194283/255d40ed-70df-45ce-8de4-153258fbebe6)
![VKDQO @ J5AY{30ONQ T875](https://github.com/BUAABIGSCity/PDFormer/assets/130194283/3a88d7ac-ea11-47fe-b928-a7bcca971782)
上图显示测试集划分时共包含3394组数据，而模型最终输出的.npz预测文件中，却预测了3408组数据，请问这是什么原因？我在使用libcity库的时候也遇到了同样的问题，感谢解答！

**Comment by siyuan1127** [comment]
使用的是PEMS04数据集

**Comment by aptx1231** [comment]
Batch size设置的多少？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: siyuan1127 ***@***.***&gt;
发送时间: 2023年10月3日 15:30
收件人: BUAABIGSCity/PDFormer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [BUAABIGSCity/PDFormer] 关于数据集划分的测试集test和最终输出的预测npz文件中数量不一致的问题 (Issue #15)





 

 
 上图显示测试集划分时共包含3394组数据，而模型最终输出的.npz预测文件中，却预测了3408组数据，请问这是什么原因？我在使用libcity库的时候也遇到了同样的问题，感谢解答！

**Comment by siyuan1127** [comment]
> Batch size设置的多少？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: siyuan1127 ***@***.***&gt; 发送时间: 2023年10月3日 15:30 收件人: BUAABIGSCity/PDFormer ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [BUAABIGSCity/PDFormer] 关于数据集划分的测试集test和最终输出的预测npz文件中数量不一致的问题 (Issue #15) 上图显示测试集划分时共包含3394组数据，而模型最终输出的.npz预测文件中，却预测了3408组数据，请问这是什么原因？我在使用libcity库的时候也遇到了同样的问题，感谢解答！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

发现问题了，是因为最后一个batch数据不满，因此自动填充了，感谢指点！

**Comment by siyuan1127** [comment]
> Batch size设置的多少？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: siyuan1127 ***@***.***&gt; 发送时间: 2023年10月3日 15:30 收件人: BUAABIGSCity/PDFormer ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [BUAABIGSCity/PDFormer] 关于数据集划分的测试集test和最终输出的预测npz文件中数量不一致的问题 (Issue #15) 上图显示测试集划分时共包含3394组数据，而模型最终输出的.npz预测文件中，却预测了3408组数据，请问这是什么原因？我在使用libcity库的时候也遇到了同样的问题，感谢解答！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

发现问题了，是因为最后一个batch数据不满，因此自动填充了，感谢指点！

**Comment by siyuan1127** [comment]
> Batch size设置的多少？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: siyuan1127 ***@***.***&gt; 发送时间: 2023年10月3日 15:30 收件人: BUAABIGSCity/PDFormer ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [BUAABIGSCity/PDFormer] 关于数据集划分的测试集test和最终输出的预测npz文件中数量不一致的问题 (Issue #15) 上图显示测试集划分时共包含3394组数据，而模型最终输出的.npz预测文件中，却预测了3408组数据，请问这是什么原因？我在使用libcity库的时候也遇到了同样的问题，感谢解答！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

发现问题了，是因为最后一个batch数据不满，因此自动填充了，感谢指点！

**Comment by siyuan1127** [comment]
> Batch size设置的多少？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: siyuan1127 ***@***.***&gt; 发送时间: 2023年10月3日 15:30 收件人: BUAABIGSCity/PDFormer ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [BUAABIGSCity/PDFormer] 关于数据集划分的测试集test和最终输出的预测npz文件中数量不一致的问题 (Issue #15) 上图显示测试集划分时共包含3394组数据，而模型最终输出的.npz预测文件中，却预测了3408组数据，请问这是什么原因？我在使用libcity库的时候也遇到了同样的问题，感谢解答！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

你好，你们论文里复现的TFormer有计划在libcity库上更新吗？原论文使用的是METR_LA数据集，我尝试更换PEMS04后，实验结果与PDFormer论文提供的有很大差距，想要参考一下你们是如何复现的。
