### ISSUE TITLE
关于比较模型实验结果的一些问题。

### ISSUE THREAD

**Issue by Transformer0714** [BUAABIGSCity/PDFormer#16]
首先非常感谢你们出色的研究工作，给了我很多帮助。Libcity的主页上说此工作是基于Libcity进行开发的，我在使用libcity进行模型实验的时候，发现实验结果与本篇论文所给结果有较大出入，比如STTN模型在PeMS08数据集上的MAE为16.90，而本文的结果为15.482。请问你们是在libcity的模型中进行了参数调优吗？

**Comment by Transformer0714** [comment]
另外还有一个关于Libcity库的问题，我在使用其介绍里下载的PEMSD8数据集和PDFormer提供的PeMS08数据集进行实验时，得到的结果截然不同，请问这两个数据集有什么区别吗？
![屏幕截图 2023-10-05 105534](https://github.com/BUAABIGSCity/PDFormer/assets/147016008/92eba444-d0d7-471a-b387-ce926e2569ae)
PEMSD8得到的结果6.4976看起来与流量、速度和占有率的预测结果都不吻合

**Comment by aptx1231** [comment]
这是因为没有区分速度、流量、占有率，https://github.com/LibCity/Bigscity-LibCity/issues/358 这里介绍了如何区分这3类数据。
这个仓库提供的pemsd8数据集是默认区分了数据的，而libcity里边提供的数据集没有区分，需要手动修改一下。

论文确实做了参数调优，另外需要注意的是libcity默认的数据划分比例是712，而本文遵循过去对于pemsd4/8的设置，采用的622，因此结果可能不同。另外，也可以看下是否区分了交通数据的类型。

**Comment by Transformer0714** [comment]
好的，非常感谢，明白了。

**Comment by Transformer0714** [comment]
还有一个问题，libcity中目前复现的模型是使用的原论文的参数吗？我跑了几个模型发现和PDFormer所给的结果都有一些差距

**Comment by aptx1231** [comment]
libcity是基于原论文的参数，但是比较粗糙，比如多个数据集是同一套参数。所以libcity并不完全能复现原始性能，会差一点。

**Comment by Transformer0714** [comment]
非常感谢您的耐心解答！
