### ISSUE TITLE
您好，请问为什么我训练PEMS08那个数据集的时候一开始加载数据的shape在特征维度那块是9呢？shape=train x: (10700, 12, 170, 9), y: (10700, 12, 170, 9)

### ISSUE THREAD

**Issue by klayc-gzl** [BUAABIGSCity/PDFormer#17]
您好，请问为什么我训练PEMS08那个数据集的时候一开始加载数据的shape在特征维度那块是9呢？shape=train x: (10009, 12, 307, 9), y: (10009, 12, 307, 9)

**Comment by klayc-gzl** [comment]
![9`{`4Y)YHE E L{(I7W~UW6](https://github.com/BUAABIGSCity/PDFormer/assets/80515849/b47f3b55-2ae2-4d4f-b8e2-ac2bee646d31)

**Comment by klayc-gzl** [comment]
@aptx1231

**Comment by aptx1231** [comment]
因为设置了add-time-in-day和add-day-in-week哦，增加时间信息1+1+7是9。
这个问题我好像在哪看到过，我以为我回复了呢，不好意思。

**Comment by aptx1231** [comment]
add-time-in-day是增加一位是时间信息
add-day-in-week是增加7位的星期信息
