### ISSUE TITLE
Could you support a pre-trained model?

### ISSUE THREAD

**Issue by yanshuaibupt** [BUAABIGSCity/PDFormer#2]
Thanks for your excellent job, I cost a lot of time on training the model on my device. Could you upload a pre-trained model?

**Comment by aptx1231** [comment]
抱歉回复的比较晚，才看到issue。我提供pems04和nyxtaxi的预训练模型。注意论文的结果是多次实验的平均值，下边提供的只是一次实验产出的预训练模型哦。

[PDFormer_PeMS04.zip](https://github.com/BUAABIGSCity/PDFormer/files/11107380/PDFormer_PeMS04.zip)
[PDFormer_NYCTaxi.zip](https://github.com/BUAABIGSCity/PDFormer/files/11107381/PDFormer_NYCTaxi.zip)
