### ISSUE TITLE
关于使用PeMS07 出现killed问题

### ISSUE THREAD

**Issue by klayc-gzl** [BUAABIGSCity/PDFormer#20]
您好，我使用PeMS07进行训练，但是会出现killed，这应该是超内存了吧，我的内存只有24G，请问有没有什么办法能够调整一下PeMS
07的输入呢

**Comment by klayc-gzl** [comment]
您在pdformer中进行对比的其它模型可以通过libcity复现吗

**Comment by aptx1231** [comment]
> 您好，我使用PeMS07进行训练，但是会出现killed，这应该是超内存了吧，我的内存只有24G，请问有没有什么办法能够调整一下PeMS

24G可能有点费劲，可以试试设置add-day-in-week是false，损失部分精度。

**Comment by aptx1231** [comment]
> 您在pdformer中进行对比的其它模型可以通过libcity复现吗

可以的，运行libcity就行了。

**Comment by klayc-gzl** [comment]
好的好的，谢谢您，还有一个问题是请问您论文所给出的结果都是用的MASK的值吗？

**Comment by aptx1231** [comment]
对的，这个是通用做法。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: klayc-gzl ***@***.***&gt;
发送时间: 2023年10月18日 19:04
收件人: BUAABIGSCity/PDFormer ***@***.***&gt;
抄送: Jiawei Jiang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [BUAABIGSCity/PDFormer] 关于使用PeMS07 出现killed问题 (Issue #20)





 
好的好的，谢谢您，还有一个问题是请问您论文所给出的结果都是用的MASK的值吗？

**Comment by klayc-gzl** [comment]
不好意思，还想再请教一下，因为您在add_time_in_day中其实是增加一个维度的时间信息，但是周期信息用的one-hot，然后现在我不是内存不太够吗，我就想将week也放进一个维度用0-6表示
![image](https://github.com/BUAABIGSCity/PDFormer/assets/80515849/375873db-32e9-49ff-b490-0b069cbaa78e)
![image](https://github.com/BUAABIGSCity/PDFormer/assets/80515849/f57bcb53-d776-4a45-835e-4e1c06f6ef77)
然后我看它维度确实变成3了：
![image](https://github.com/BUAABIGSCity/PDFormer/assets/80515849/7abfea7c-fd4a-453a-89af-78f28791f084)
但是最后结果会出现一种奇怪的错误：
![image](https://github.com/BUAABIGSCity/PDFormer/assets/80515849/c8050fbe-abb0-484a-8a70-327e8b7ec019)
太感谢您了！！！

**Comment by klayc-gzl** [comment]
将维度修改后不知道为什么会出现这种错误
![image](https://github.com/BUAABIGSCity/PDFormer/assets/80515849/b18d8eaf-0c13-4150-869b-f02f0310958c)

**Comment by klayc-gzl** [comment]
和下面这种错误
![image](https://github.com/BUAABIGSCity/PDFormer/assets/80515849/64fc9ac2-0dd2-4e9b-8147-95692245845f)

**Comment by klayc-gzl** [comment]
已解决，非常感谢作者！
