### ISSUE TITLE
文件获取

### ISSUE THREAD

**Issue by klayc-gzl** [BUAABIGSCity/PDFormer#22]
作者您好，请问您可以提供一下生成好的PeMS07数据文件吗，设备有限，老是在生成这个文件的时候killed。
![image](https://github.com/BUAABIGSCity/PDFormer/assets/80515849/94cc24ef-8666-4430-8dde-1f67be859c4a)

**Comment by klayc-gzl** [comment]
还有请问一下作者，我从您们libcity里面下载了PeMS03的数据集，然后想用pdformer进行实验，但是无法运行成功，您们当时没有使用PeMS03的数据集实验是怎么考虑的呢

**Comment by aptx1231** [comment]
第一个问题的话，还是建议把add-day-in-week设置false，这样生产的时候文件就变小了。否则你load这个文件，内存也不够。

**Comment by aptx1231** [comment]
第二个问题，libcity下载的pems03是可以跑的，出现了什么错误？没用这个是因为aaai页数限制

**Comment by klayc-gzl** [comment]
主要就是邻接矩阵那有点问题：
![98b80c08eee4a911bf3ced08669b50f](https://github.com/BUAABIGSCity/PDFormer/assets/80515849/7b25ba29-7f6e-4b77-a0c5-1029adcb2ba3)

**Comment by klayc-gzl** [comment]
您好，是因为json文件写的有问题吗，感觉和其它差不多

**Comment by aptx1231** [comment]
看起来就是这个全连接计算的时候有问题，有一个维度是0，大概率就是输入的lap_mx某个维度变成0了，说明计算有问题。

这个你单步debug一下吧，应该可以发现具体的问题

**Comment by aptx1231** [comment]
拉普莱斯矩阵计算的代码：https://github.com/BUAABIGSCity/PDFormer/blob/master/libcity/executor/pdformer_executor.py#L71

**Comment by klayc-gzl** [comment]
但其它三个数据集都能运行诶

**Comment by klayc-gzl** [comment]
我debug发现，其它三个数据集中isolated_point_num计算出来的结果都是0，但是PeMS03数据集中计算出来的这个值是顶点个数也就是358，这导致再后面laplacian_pe = torch.from_numpy(EigVec[:, isolated_point_num + 1: self.lape_dim + isolated_point_num + 1]).float()取值的时候超出范围，所以维度变成了(358，0)。
