### ISSUE TITLE
请问如何画出来与论文中类似的热力图

### ISSUE THREAD

**Issue by xnnnna** [BUAABIGSCity/PDFormer#23]

**Comment by aptx1231** [comment]
保存attention map的输出，然后使用matplotlib的imshow函数就行了

**Comment by aptx1231** [comment]
就类似https://github.com/BUAABIGSCity/PDFormer/blob/master/libcity/model/traffic_flow_prediction/PDFormer.py#L198 这里softmax之后的attention map

**Comment by yhl2018** [comment]
@aptx1231 可以提供更详细点的示例吗？

**Comment by KKKKK-yu** [comment]
> @aptx1231 可以提供更详细点的示例吗？

您好，请问您画出来了吗，我也有此困惑
