### ISSUE TITLE
hello,I want to ask you if your code can get sensor_id's location

### ISSUE THREAD

**Issue by xumeng1003** [BUAABIGSCity/PDFormer#3]

**Comment by aptx1231** [comment]
这个不太行，因为这些数据集本身都没有提供sensor的位置，只提供sensor的链接关系

**Comment by xumeng1003** [comment]
好吧，谢谢您的回复



---Original---
From: "Jiawei ***@***.***&gt;
Date: Thu, Mar 30, 2023 00:12 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BUAABIGSCity/PDFormer] hello,I want to ask you if your code canget sensor_id's location (Issue #3)




 
这个不太行，因为这些数据集本身都没有提供sensor的位置，只提供sensor的链接关系

**Comment by aptx1231** [comment]
需要带位置的数据集的话，可以用metr-la，pems-bay数据集。参考这里：https://github.com/LibCity/Bigscity-LibCity-Datasets

**Comment by xumeng1003** [comment]
嗯嗯好，那我换个数据集试试，谢谢您啊



---Original---
From: "Jiawei ***@***.***&gt;
Date: Thu, Mar 30, 2023 00:15 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BUAABIGSCity/PDFormer] hello,I want to ask you if your code canget sensor_id's location (Issue #3)




 
需要带位置的数据集的话，可以用metr-la，pems-bay数据集。参考这里：https://github.com/LibCity/Bigscity-LibCity-Datasets
