### ISSUE TITLE
如何在PDFormer上运行PEMS03/METR-LA/PEMS-Bay等数据集

### ISSUE THREAD

**Issue by huangst21** [BUAABIGSCity/PDFormer#32]
作者们是否有尝试过在PDFormer上运行PEMS03/METR-LA/PEMS-Bay等数据集呢? 想把这几个数据集也跑一下

**Comment by aptx1231** [comment]
直接跑就可以了，从libcity仓库下载数据集

**Comment by Ethereal-sakura** [comment]
新手小白求问，对于新的数据集的json文件应该怎么配置呢？
