### ISSUE TITLE
AttributeError: dataset_class is not found

### ISSUE THREAD

**Issue by sopphia2001** [BUAABIGSCity/PDFormer#39]
您好作者，我在复现代码的时候，出现了AttributeError: dataset_class is not found问题，请问作者怎么解决？

 File "E:\文献代码\PDFormer-master\libcity\data\utils.py", line 16, in get_dataset
    raise AttributeError('dataset_class is not found')
AttributeError: dataset_class is not found

<img width="382" alt="屏幕截图 2024-03-11 145022" src="https://github.com/BUAABIGSCity/PDFormer/assets/145556564/16d18ef2-8e52-4c81-a4d2-0213d7ca64f6">

<img width="470" alt="屏幕截图 2024-03-11 145818" src="https://github.com/BUAABIGSCity/PDFormer/assets/145556564/e6f1692d-8552-41a2-a11c-f12a3a356329">

**Comment by horizon12138** [comment]
您好，我也遇到了同样的问题，请问您是怎么解决的呢？

**Comment by MaoViolet** [comment]
> 您好作者，我在复现代码的时候，出现了AttributeError： dataset_class is not found问题，请问作者怎么解决？
> 
> 文件“E：\文献代码\PDFormer-master\libcity\data\utils.py”，第 16 行，get_dataset引发 AttributeError（'dataset_class is not found'） AttributeError： dataset_class is not found
> 
> <img alt="屏幕截图 2024-03-11 145022" width="382" src="https://private-user-images.githubusercontent.com/145556564/311610496-16d18ef2-8e52-4c81-a4d2-0213d7ca64f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTQxODksIm5iZiI6MTcxMzUxMzg4OSwicGF0aCI6Ii8xNDU1NTY1NjQvMzExNjEwNDk2LTE2ZDE4ZWYyLThlNTItNGM4MS1hNGQyLTAyMTNkN2NhNjRmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwODA0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGIzZDNmZGViYmYxMjZmN2MxYmRmY2E1MGU2MmVhYjA5NDZkNzUxZTUyMWM2Yjc0YmRiNGU3OWY2OTI0OGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.orlwiXENPfDDHepoMEeRmcqIMD7wlh6hOOSyG27IIdA"> <img alt="屏幕截图 2024-03-11 145818" width="470" src="https://private-user-images.githubusercontent.com/145556564/311612475-e6f1692d-8552-41a2-a11c-f12a3a356329.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTQxODksIm5iZiI6MTcxMzUxMzg4OSwicGF0aCI6Ii8xNDU1NTY1NjQvMzExNjEyNDc1LWU2ZjE2OTJkLTg1NTItNDFhMi1hMTFjLWYxMmEzYTM1NjMyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwODA0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWIwNmEyYzBkMDBhNGU1OGJiYTNjYjdkMjQ5M2YxNzE5NmZlMmJmNWU4YjRmNmFkNTdlYWU4NTk1YTNkOWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yk2rXut645nPL3aQr_6ETJKlOsrwupKPlpzJ9rcNkjU">

请问您是怎么解决的呢
