### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './raw_data/METR_LA/config.json'

### ISSUE THREAD

**Issue by KKKKK-yu** [BUAABIGSCity/PDFormer#45]
在复现时遇到这个报错，但是论文中并没有用到METR_LA数据集，是把数据集名称改掉还是自己添加这个数据集呢？

**Comment by 1zhd** [comment]
> 在复现时遇到这个报错，但是论文中并没有用到METR_LA数据集，是把数据集名称改掉还是自己添加这个数据集呢？

请问楼主有解决这个问题吗？我复现的时候也遇到了这个情况，期待楼主回复，谢谢！

**Comment by KKKKK-yu** [comment]
好像是把数据集换成作者给的数据集就行了，把模型中相应代码改成对应数据集就行
















在 2024-07-27 15:15:01，"1zhd" ***@***.***> 写道：

在复现时遇到这个报错，但是论文中并没有用到METR_LA数据集，是把数据集名称改掉还是自己添加这个数据集呢？

请问楼主有解决这个问题吗？我复现的时候也遇到了这个情况，期待楼主回复，谢谢！

**Comment by 1zhd** [comment]
好的&nbsp; 感谢楼主！



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 27, 2024 15:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BUAABIGSCity/PDFormer] FileNotFoundError: [Errno 2] No such fileor directory: './raw_data/METR_LA/config.json' (Issue #45)




 好像是把数据集换成作者给的数据集就行了，把模型中相应代码改成对应数据集就行
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 在 2024-07-27 15:15:01，"1zhd" ***@***.***&gt; 写道：
 
 在复现时遇到这个报错，但是论文中并没有用到METR_LA数据集，是把数据集名称改掉还是自己添加这个数据集呢？
 
 请问楼主有解决这个问题吗？我复现的时候也遇到了这个情况，期待楼主回复，谢谢！
