### ISSUE TITLE
process non-traffic data

### ISSUE THREAD

**Issue by LittleTigger-alpha** [BUAABIGSCity/PDFormer#5]
Can PDFormer handle non-traffic data, such as ECG500 or electricity. There is no geographical distance relationship between variables, but there may be an implicit relationship. If the model can process, how to process these datasets? Your help would be much appreciated!

**Comment by aptx1231** [comment]
It should work, but you need to process the code to remove the geographic distance mask matrix (which is the `geo_mask` in the code) and keep only the semantic mask matrix. In that case, the attention mechanism will only keep the semantic spatial attention as well. For data processing, just process into atomic files, and refer to the [libcity documentation](https://bigscity-libcity-docs.readthedocs.io/en/latest/user_guide/data/atomic_files.html) for the definition of the format.

Besides, you can refer to the [LibCity](https://github.com/LibCity/Bigscity-LibCity) repository and the [KDD CUP](https://github.com/BUAABIGSCity/KDDCUP2022) repository we developed, which have many spatio-temporal prediction methods that are suitable for dealing with such multivariate temporal prediction problems with implicit dependencies.
