### ISSUE TITLE
Error about the datasets

### ISSUE THREAD

**Issue by RootChenLQ** [BUAABIGSCity/PDFormer#6]
An error happened when running "python run_model.py --task traffic_state_pred --model PDFormer --dataset PeMS04 --config_file PeMS04"

"FileNotFoundError: [Errno 2] No such file or directory: './raw_data/PeMS04/P.dyna'"

There is no P.dyna file in the datasets downloaded from Google Drive. So where can we obtain P.dyna files?

**Comment by aptx1231** [comment]
![image](https://github.com/BUAABIGSCity/PDFormer/assets/35984903/e0faf2df-aa14-4e36-87c7-50c5cf2874e9)

The downloaded dataset contains dyna files.

The directory structure should look like this. Please check:

libcity/
raw_data/PeMS04/PeMS04.geo
raw_data/PeMS04/PeMS04.rel
raw_data/PeMS04/PeMS04.dyna
run_model.py
